#------------------------------------------------------
# Copyright (c) 2025, Elehobica
# Released under the BSD-2-Clause
# refer to https://opensource.org/licenses/BSD-2-Clause
#------------------------------------------------------

name: Build

on: [push, pull_request]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build Pico
        uses: elehobica/build-pico@v1
        with:
          build: build
      - name: Move artifacts for Pico
        uses: elehobica/add-identifier@v1
        with:
          paths: ./build
          exts: .uf2 .elf .elf.map
          identifier: pico
      - name: Build Pico 2
        uses: elehobica/build-pico@v1
        with:
          build: build2
          platform: rp2350
          board: pico2
      - name: Move artifacts for Pico 2
        uses: elehobica/add-identifier@v1
        with:
          paths: ./build2
          exts: .uf2 .elf .elf.map
          identifier: pico2
      - name: Upload production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-binaries
          path: |
            build*/*.uf2
            build*/*.elf