#------------------------------------------------------
# Copyright (c) 2025, Elehobica
# Released under the BSD-2-Clause
# refer to https://opensource.org/licenses/BSD-2-Clause
#------------------------------------------------------

name: Build

on: [push, pull_request]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build Pico
        uses: elehobica/build-pico@v1
        with:
          build: build
      - name: Move artifacts for Pico
        run: |
          cd $build
          AddIdentifier=-$Target-$GITHUB_REF_NAME
          if [ $GITHUB_REF_TYPE = "branch" ]; then
            AddIdentifier=$AddIdentifier-${{github.run_number}}
          fi
          for ext in .uf2 .elf .elf.map; do
            mv $(ls *$ext) $(basename $(ls *$ext) $ext)$AddIdentifier$ext
          done
        env:
          build: build
          Target: pico
      - name: Build-pico2
        uses: elehobica/build-pico@v1
        with:
          build: build2
          platform: rp2350
          board: pico2
      - name: Move artifacts for Pico 2
        run: |
          cd $build
          AddIdentifier=-$Target-$GITHUB_REF_NAME
          if [ $GITHUB_REF_TYPE = "branch" ]; then
            AddIdentifier=$AddIdentifier-${{github.run_number}}
          fi
          for ext in .uf2 .elf .elf.map; do
            mv $(ls *$ext) $(basename $(ls *$ext) $ext)$AddIdentifier$ext
          done
        env:
          build: build2
          Target: pico2
      - name: Upload production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-binaries
          path: |
            build*/*.uf2
            build*/*.elf